name: scheduled-python

on:
  schedule:
    #- cron: '4 0 * * *'   # 毎日00:04 UTC → JST の 09:04 に相当
    #- cron: '24 2 * * *'  # 毎日02:24 UTC → JST の 11:24 に相当
    - cron: '12 3 * * *'  # 毎日02:24 UTC → JST の 12:12 に相当
    - cron: '31 4 * * *'  # 毎日02:24 UTC → JST の 13:31 に相当
    - cron: '39 4 * * *'  # 毎日02:24 UTC → JST の 13:39 に相当
    #- cron: '24 6 * * *'  # 毎日02:24 UTC → JST の 15:24 に相当
    # - cron: '24 7 * * *'  # 毎日02:24 UTC → JST の 16:24 に相当
    #- cron: '24 8 * * *'  # 毎日02:24 UTC → JST の 17:24 に相当
    #- cron: '24 9 * * *'  # 毎日02:24 UTC → JST の 18:24 に相当
    #- cron: '24 10 * * *'  # 毎日02:24 UTC → JST の 19:24 に相当
    #- cron: '24 11 * * *'  # 毎日02:24 UTC → JST の 20:24 に相当
    #- cron: '24 12 * * *'  # 毎日02:24 UTC → JST の 21:24 に相当
    #- cron: '24 13 * * *'  # 毎日02:24 UTC → JST の 22:24 に相当
    #- cron: '24 14 * * *'  # 毎日02:24 UTC → JST の 23:24 に相当
    #- cron: '24 15 * * *'  # 毎日02:24 UTC → JST の 24:24 に相当
    #- cron: '24 16 * * *'  # 毎日02:24 UTC → JST の 25:24 に相当
    #- cron: '24 17 * * *'  # 毎日02:24 UTC → JST の 26:24 に相当
    #- cron: '24 18 * * *'  # 毎日02:24 UTC → JST の 27:24 に相当
    #- cron: '24 19 * * *'  # 毎日02:24 UTC → JST の 28:24 に相当
  workflow_dispatch:     # 手動実行用（テスト用）

jobs:
  run-python:
    runs-on: ubuntu-latest
    concurrency:
      group: scheduled-python
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scheduled script
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          python scripts/main.py
