name: scheduled-python

on:
  schedule:
    - cron: '14 0 * * *'  # 毎日00:14 UTC → JST の 09:14 に相当
    #- cron: '24 1 * * *'  # 毎日01:24 UTC → JST の 10:24 に相当
    #- cron: '12 2 * * *'  # 毎日02:14 UTC → JST の 11:12 に相当
    #- cron: '21 3 * * *'  # 毎日03:24 UTC → JST の 12:21 に相当
    #- cron: '19 4 * * *'  # 毎日04:14 UTC → JST の 13:19 に相当
    #- cron: '24 5 * * *'  # 毎日05:24 UTC → JST の 14:24 に相当
    #- cron: '14 6 * * *'  # 毎日06:14 UTC → JST の 15:14 に相当
    #- cron: '24 7 * * *'  # 毎日07:24 UTC → JST の 16:24 に相当
    #- cron: '14 8 * * *'  # 毎日08:14 UTC → JST の 17:14 に相当
    #- cron: '24 9 * * *'  # 毎日09:24 UTC → JST の 18:24 に相当
    #- cron: '14 10 * * *'  # 毎日10:14 UTC → JST の 19:14 に相当
    #- cron: '24 11 * * *'  # 毎日11:24 UTC → JST の 20:24 に相当
    #- cron: '14 12 * * *'  # 毎日12:14 UTC → JST の 21:14 に相当
    #- cron: '24 13 * * *'  # 毎日13:24 UTC → JST の 22:24 に相当
    #- cron: '14 14 * * *'  # 毎日14:14 UTC → JST の 23:14 に相当
    #- cron: '24 15 * * *'  # 毎日15:24 UTC → JST の 24:24 に相当
    #- cron: '14 16 * * *'  # 毎日16:14 UTC → JST の 25:14 に相当
    #- cron: '24 17 * * *'  # 毎日17:24 UTC → JST の 26:24 に相当
    #- cron: '14 18 * * *'  # 毎日18:14 UTC → JST の 27:24 に相当
    #- cron: '24 19 * * *'  # 毎日19:24 UTC → JST の 28:24 に相当
    #- cron: '14 20 * * *'  # 毎日20:14 UTC → JST の 29:14 に相当
    #- cron: '24 21 * * *'  # 毎日21:24 UTC → JST の 30:24 に相当
    #- cron: '14 22 * * *'  # 毎日22:14 UTC → JST の 31:14 に相当
    #- cron: '24 23 * * *'  # 毎日23:24 UTC → JST の 32:24 に相当
  workflow_dispatch:     # 手動実行用（テスト用）

jobs:
  run-python:
    runs-on: ubuntu-latest
    concurrency:
      group: scheduled-python
      cancel-in-progress: true

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run scheduled script
        env:
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: |
          python scripts/main.py
